apiVersion : apps/v1
kind: Deployment
metadata:
  name: "trellis-b7c4"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: "trellis-b7c4"
  template:
    metadata:
      labels:
        app: "trellis-b7c4"
    spec:
      containers:
        - name: "trellis-b7c4"
          image: "acrtrellis.azurecr.io/trellis"
          ports:
          - containerPort: 80